### PR TITLE
Revised schema

### PR DESCRIPTION
**Pull request by maguina-sj**

### CODE REVIEW

**Review by snepderg — DISMISSED** [review]
Looks good to me, namely adds the updated page_turners.sql, with some residual changes from the other branch. Easy fix.

**Review by snepderg — APPROVED** [review]

**Review by snepderg — DISMISSED** [review]
I don't know why it won't let me approve it, it's stale before the merge base apparently?

**Review by Micah-G8864 — APPROVED** [review]
looks great

**Review by Micah-G8864 — DISMISSED** [review]

**Comment by snepderg** [comment]
We had some unforeseen issues with this PR, to prevent delays I'm closing it so we can redo the addition of the new schema.

**Pull request closed without merging**
